---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define tomcat8_home
  set_fact:
    tomcat8_home: "{{ __tomcat8_home }}"
  when: tomcat8_home is not defined

- name: Define tomcat8_version
  set_fact:
    tomcat8_version: "{{ __tomcat8_version }}"
  when: tomcat8_version is not defined

- name: Define tomcat_binary_url
  set_fact:
    tomcat_binary_url: "{{ __tomcat_binary_url }}"
  when: tomcat_binary_url is not defined

- name: Define tomcat_target_dir
  set_fact:
    tomcat_target_dir: "{{ __tomcat_target_dir }}"
  when: tomcat_target_dir is not defined

- include: "install-{{ ansible_os_family }}.yml"
  tags:
    - tomcat8
    - tomcat8-install

- include: config.yml
  static: no
  tags:
    - tomcat8
    - tomcat8-config
